server: 
  port: 8081
  servlet: 
    context-path: /resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/skent
          jwk-set-uri: http://localhost:8083/auth/realms/skent/protocol/openid-connect/certs